### ISSUE TITLE
I wanna add support to Tiger Lake

### ISSUE THREAD

**Issue by macsupermac** [ChefKissInc/NootedBlue#10]
As we know,Apple has given up the support for Tiger Lake,but Iris Xe Graphics is powerful,I hope NootInc can support Tiger Lake.You have already developed the drivers for AMD Vega Graphics.Thank you for your efforts!!!

**Comment by notluke27** [comment]
Same. I have a 12th gen core i5 laptop (alder lake) with iris xe.

**Comment by Zormeister** [comment]
Duplicate of #6.
