### ISSUE TITLE
Add support for Ivy bridge systems that are using a VGA cable

### ISSUE THREAD

**Issue by cornshiba** [ChefKissInc/NootedBlue#12]
I tried hackintoshing my i7-3770 pc but it got stuck at `IOConsoleUsers: gIOScreenLockState 3, hs 0, bs 0, now 0, sm 0x0`, after reading WhateverGreen's manual for Intel HD iGPUs. i noticed VGA isn't supported on Ivy Bridge systems since Mac OS X Mountain lion 10.8.2. So i'd greatly appreciate it if you add support for it. Thanks!

**Comment by Zormeister** [comment]
we don’t support 10.8.X, only 10.14+ is supported (and doesn’t even work yet) on Broadwell (Intel Core i5th generation) and newer

**Comment by cornshiba** [comment]
Ah okay, thanks.
